# Use an official Python runtime as a parent image
FROM python:3.7-slim

# Set the working directory to /home
WORKDIR /home

# Copy the current directory contents into the container at /home
COPY . /home

# Run heart when the container launches
CMD ["python", "heart"]
